name: Build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        name: 'General Build (PHP: 7.4)'
        runs-on: ubuntu-latest
        steps:
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    extension-csv: mbstring, xml, ctype, iconv, mysql, curl, intl
                    coverage: pcov
            -   uses: actions/checkout@v1
            -   uses: ramsey/composer-install@v1

    php_stan:
        name: 'PHP Stan'
        runs-on: ubuntu-latest
        steps:
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    extension-csv: mbstring, xml, ctype, iconv, mysql, curl, intl
                    coverage: pcov
            -   uses: actions/checkout@v1
            -   uses: ramsey/composer-install@v1
            -   name: PHP Stan
                run: bin/phpstan analyze

    psalm:
        name: 'Psalm'
        runs-on: ubuntu-latest
        steps:
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    extension-csv: mbstring, xml, ctype, iconv, mysql, curl, intl
                    coverage: pcov
            -   uses: actions/checkout@v1
            -   uses: ramsey/composer-install@v1
            -   name: Psalm
                run: bin/psalm

    php_unit:
        name: 'PHP Unit'
        runs-on: ubuntu-latest
        steps:
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    extension-csv: mbstring, xml, ctype, iconv, mysql, curl, intl
                    coverage: pcov
            -   uses: actions/checkout@v1
            -   uses: ramsey/composer-install@v1
            -   name: PHPUnit
                run: bin/phpunit

