name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Composer
      -   name: Validate composer.json and composer.lock
          run: composer validate

      -   name: Install Composer dependencies
          run: composer install --dev --no-progress --no-suggest --prefer-dist --optimize-autoloader



      # https://github.com/chekalsky/phpcs-action (community)
      - name: Check PSR12 code style (PHP_CodeSniffer)
        uses: chekalsky/phpcs-action@v1.2.0
        with:
          enable_warnings: true
          installed_paths: '${{ github.workspace }}/vendor/squizlabs/php_codesniffer'
          phpcs_bin_path: './bin/phpcs'

      # https://github.com/phpstan/phpstan
      - name: Analyse PHP Code (PHPStan)
        run: vendor/bin/phpstan analyse

      - name: Analyse PHP code (psalm)
        run: bin/psalm

      # Tests
      - name: Run unit and functional tests
        run: |
          php bin/phpunit --stop-on-failure
